name: Java CI-CD Pipeline

on:
  push:
    branches:
      - master

  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-1       
  ECR_REPOSITORY: devops-app-repo            
  ECS_CLUSTER_NAME: ips-cluster

jobs:
  ci-cd:
    runs-on: ubuntu-latest       

    steps:

########################################
# 1. Checkout Code
########################################
    - name: Checkout Code
      uses: actions/checkout@v3

########################################
# 2. Setup Java
########################################
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: maven

########################################
# 3. Build Application
########################################
    - name: Build Maven
      run: mvn clean install

########################################
# 4. SonarQube Scan
########################################
    - name: SonarQube Scan
      run: |
        mvn sonar:sonar \
        -Dsonar.projectKey=my-java-app \
        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

########################################
# 5. Configure AWS
########################################
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

########################################
# 6. Login to ECR
########################################
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

########################################
# 7. Build Docker Image
########################################
    - name: Build Docker Image
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest .

########################################
# 8. Trivy Scan
########################################
    - name: Scan Image using Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
        format: table
        severity: CRITICAL,HIGH
        exit-code: 0

########################################
# 9. Push Image to ECR
########################################
    - name: Push Image to ECR
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
        - name: Update ECS Task Definition
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          sed -i "s|<IMAGE>|$ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}|g" task-definition.json
          cat task-definition.json > new-task.json

    - name: Deploy to Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
          task-definition: new-task.json
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true
    - name: Update ECS Task Definition
      run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          sed -i "s|<IMAGE>|$ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}|g" task-definition.json
          cat task-definition.json > new-task.json

    - name: Deploy to Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
          task-definition: new-task.json
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true
